[tool.ruff]
target-version = "py312"
line-length = 100
extend-exclude = ["migrations", "build", "dist", "node_modules", ".venv"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "PL", "RUF"]
ignore = [
  "E203", 
  "B008"
]

[tool.ruff.lint.isort]
known-first-party = ["app"]
