name: CI

on:
  push:
    branches: ["**"]
    paths:
      - "./**"
      - "docker-compose.yml"
      - ".github/workflows/docker.yml"
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker versions (debug)
        run: |
          docker version
          docker compose version

      - name: Build containers
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker compose --env-file .env build --pull

      # ----- Closing -----
      - name: Cleanup
        env:
          DOCKER_BUILDKIT: 1
        if: always()
        run: |
          docker compose --env-file .env  down -v --remove-orphans